from .cadastro import CadastroScreen
from .configura import ConfiguraScreen
from .jogo import JogoScreen
from .login import LoginScreen
from .menu import MenuScreen
from .personalizado import PersonalizadoScreen
from .splash import SplashScreen
from .temas import TemasScreen
from data.database import Database
